<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ContractWebForm.aspx.cs" Inherits="WebApplication1.ContractWebForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <p>Contact Form</p>
            <div class="col-sm-12">
            <div class="col-sm-4">
                <label>Contact ID</label>
                <asp:TextBox ID="ID" runat="server"></asp:TextBox>
            </div>
                <div class="col-sm-4">
                <label>Contact Name</label>
                <asp:TextBox ID="Name" runat="server"></asp:TextBox>
            </div>
                <div class="col-sm-4">
                <label>Contact City</label>
                <asp:TextBox ID="City" runat="server"></asp:TextBox>
            </div>
                <div class="col-sm-4">
                <label>Contact Email</label>
                <asp:TextBox ID="Email" runat="server"></asp:TextBox>
            </div>
                <div class="col-sm-4">
                <label>Contact DOB</label>
                <asp:TextBox ID="DOB" runat="server"></asp:TextBox>
            </div>
                <div class="col-sm-4">
                <label>Contact NUM</label>
                <asp:TextBox ID="NUM" runat="server"></asp:TextBox>
            </div>
                 <div class="col-sm-4">
               
                    <asp:Button class="btn btn-success" ID="Button2" runat="server" OnClick="Button1_Click" Text="Button" />
            </div>
                 <asp:Label ID="ResultLabel" runat="server"></asp:Label>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Pk_ContractID"
    AutoGenerateEditButton="False" AutoGenerateDeleteButton="False" 
    OnRowEditing="GridView1_RowEditing"
    OnRowUpdating="GridView1_RowUpdating"
    OnRowCancelingEdit="GridView1_RowCancelingEdit"
    OnRowDeleting="GridView1_RowDeleting"
                    BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" >
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />
                    <SortedDescendingHeaderStyle BackColor="#93451F" />
                     <Columns>
        <asp:BoundField DataField="Pk_ContractID" HeaderText="Pk_ContractID" ReadOnly="True" SortExpression="Pk_ContractID" />
        <asp:TemplateField HeaderText="ContractID">
            <ItemTemplate>
                <asp:Label ID="Label1" runat="server" Text='<%# Eval("ContractID") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("ContractID") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="ContractName">
            <ItemTemplate>
                <asp:Label ID="Label2" runat="server" Text='<%# Eval("ContractName") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("ContractName") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="City">
            <ItemTemplate>
                <asp:Label ID="Label3" runat="server" Text='<%# Eval("City") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("City") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Email">
            <ItemTemplate>
                <asp:Label ID="Label4" runat="server" Text='<%# Eval("Email") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="MobileNo">
            <ItemTemplate>
                <asp:Label ID="Label5" runat="server" Text='<%# Eval("MobileNo") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("MobileNo") %>'></asp:TextBox>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:CommandField ShowEditButton="True" ShowDeleteButton="True" />
    </Columns>
                </asp:GridView>
                
                
                </div>
            
        </div>
    </form>
</body>
</html>
