<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GuestDetials.aspx.cs" Inherits="WebApplication1.GuestDetials" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Guest Details</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <form id="form1" runat="server">
        <div class="col-sm-10" style="margin-top:20px; top: 0px; left: 0px; height: 265px; width: 1261px;">
            <asp:Label ID="Label1" runat="server"></asp:Label>
            <asp:GridView ID="GridView12" runat="server" AutoGenerateColumns="False" DataKeyNames="Pk_CustomerID"
                          AutoGenerateEditButton="False" AutoGenerateDeleteButton="False"
                          OnRowEditing="GridView12_RowEditing" OnRowUpdating="GridView12_RowUpdating"
                          OnRowCancelingEdit="GridView12_RowCancelingEdit" OnRowDeleting="GridView12_RowDeleting"
                          CssClass="table table-bordered table-striped" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
                <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FFF1D4" />
                <SortedAscendingHeaderStyle BackColor="#B95C30" />
                <SortedDescendingCellStyle BackColor="#F1E5CE" />
                <SortedDescendingHeaderStyle BackColor="#93451F" />

                <Columns>
                    <asp:BoundField DataField="Pk_CustomerID" HeaderText="Customer ID" ReadOnly="True" SortExpression="Pk_CustomerID" />
                    <asp:TemplateField HeaderText="Customer ID">
                        <ItemTemplate>
                            <asp:Label ID="LabelCID" runat="server" Text='<%# Eval("C_ID") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxCID" runat="server" Text='<%# Bind("C_ID") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Customer Name">
                        <ItemTemplate>
                            <asp:Label ID="LabelCName" runat="server" Text='<%# Eval("C_Name") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxCName" runat="server" Text='<%# Bind("C_Name") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Contact Number">
                        <ItemTemplate>
                            <asp:Label ID="LabelCNum" runat="server" Text='<%# Eval("C_Num") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxCNum" runat="server" Text='<%# Bind("C_Num") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Customer Email">
                        <ItemTemplate>
                            <asp:Label ID="LabelCEmail" runat="server" Text='<%# Eval("C_Email") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxCEmail" runat="server" Text='<%# Bind("C_Email") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Room Number">
                        <ItemTemplate>
                            <asp:Label ID="LabelRNum" runat="server" Text='<%# Eval("R_Num") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxRNum" runat="server" Text='<%# Bind("R_Num") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Created Date">
                        <ItemTemplate>
                            <asp:Label ID="LabelCreatedDate" runat="server" Text='<%# Eval("CreatedDate", "{0:dd/MM/yyyy}") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBoxCreatedDate" runat="server" Text='<%# Bind("CreatedDate", "{0:yyyy-MM-dd}") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:CommandField ShowEditButton="True" ShowDeleteButton="True" />
                </Columns>
            </asp:GridView>
            <asp:Label ID="ResultLabel" runat="server" CssClass="alert alert-info" Visible="False"></asp:Label>
        </div>
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>
