//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelCustomerDetail
    {
        public int Pk_CustomerID { get; set; }
        public int C_ID { get; set; }
        public string C_Name { get; set; }
        public string C_Num { get; set; }
        public string C_Email { get; set; }
        public Nullable<int> R_Num { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
