//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        public int Pk_ContractID { get; set; }
        public int ContractID { get; set; }
        public string ContractName { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
